- name: Install dependencies
  hosts: nezha-core				# /etc/ansible/hosts
  
  tasks:					
  - name: Ansible Update Cache and Upgrade all Packages
    register: updatesys
    apt:
      name: "*"
      state: present
      update_cache: yes
    become: yes	
  
  - name: install dependencies		
    apt: 
      name: 
        - build-essential
        - cmake
        - curl
        - tmux
        - git
        - protobuf-compiler
        - clang       # RocksDB
        - pkg-config  # RocksDB
        - libssl-dev  # RocksDB        
        - libpq-dev
      state: present
    become: yes	
  
  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust     
  
  - name: install monitoring tool
    apt:
      name:
        - htop
      state: present
    become: yes
  
  - name: add listening ports 
    shell: |
      ufw allow proto udp from any to any port 5000:6000 &&
      ufw allow proto tcp from any to any port 5000:6000
    become: yes

  - name: Clone a github repository
    git:
      repo: https://github.com/Dong-Hyeon-Yu/sui
      dest: /home/nezha/sui
      clone: yes
      update: yes